[package]
name = "static-option"
version = "0.1.0"
edition = "2018"
rust-version = "1.51"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
