on:
  push: {}
  schedule:
    - cron: '42 7 * * Tue'  # Run every wednesday at 11:16
env:
  CARGO_TERM_COLOR: always
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: clippy, rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy
  test:
    name: Full test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
      - name: Test
        run: cargo test
  test_msrv:
    name: Test with MSRV 1.64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Install MSRV
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.64
          default: true
          profile: minimal
      - name: Test
        run: cargo test
